CityOfZion/neo-tools

- README.md
- src/nodejs/neoscan/cli/get_last_block.js
- src/nodejs/neoscan/cli/get_last_block_time.js
- src/nodejs/neoscan/neoscan.js
These return the most recent block and block time in human readable format from neoscan
> get_last_block and get_last_block_time neoscan helper modules

- package.json
- src/nodejs/neon-js/cli/rpc/getconnectioncount.js
- src/nodejs/neon-js/cli/rpc/getpeers.js
- src/nodejs/neon-js/cli/rpc/getrawmempool.js
- src/nodejs/neon-js/cli/rpc/getversion.js
- src/nodejs/neon-js/cli/rpc/query.js
- src/nodejs/neon-js/cli/rpc/validateaddress.js
- src/nodejs/neoscan/cli/get_last_block_time.js
- src/nodejs/neoscan/neoscan.js
Neoscan network case-ignorance and options to use short versions like "test" and "main"
Online help for neon-js rpc cli modules updated to reflect that node option should use https://
package.json cleanup of unnecessary modules
> Updates for network and some online help changes

- README.md
- src/nodejs/neoscan/cli/get_address_abstracts.js
- src/nodejs/neoscan/cli/get_claimable.js
- src/nodejs/neoscan/cli/get_claimed.js
- src/nodejs/neoscan/neoscan.js
- get_address_abstracts
- get_claimable
- get_claimed
- Readme update
> Finished Neoscan API Support and CLI examples

- README.md
- package.json
- src/nodejs/account/account.js
- src/nodejs/account/cli/list.js
- src/nodejs/neoscan/cli/get_balance.js
- src/nodejs/neoscan/cli/get_claimable.js
- src/nodejs/neoscan/cli/get_claimed.js
- src/nodejs/neoscan/cli/get_unclaimed.js
- src/nodejs/neoscan/neoscan.js
- src/nodejs/util/debug.js
- src/nodejs/util/json.js
- src/nodejs/util/stdin.js
- stdin.js module: uniform method for accessing stdin
- json.js module: uniform json system
- neoscan/cli/get_balances.js conforms
- accounts/cli/list.js output now conforms
> CLI Chaining Neoscan Updates

- src/nodejs/account/cli/list.js
- src/nodejs/account/cli/watch.js
- list arguments
- only list address marked watch: true
- watch arguments
> Account Updates

- README.md
- package.json
- src/nodejs/account/cli/list.js
- src/nodejs/get_worth.js
- src/nodejs/neoscan/cli/get_address_abstracts.js
- src/nodejs/util/json.js
- src/nodejs/neoscan/cli/get_address_abstracts
> CSV Output Formatting and Summary Options

- src/nodejs/account/cli/list.js
forgot to remove the hardcoded key search arg
> account list debug

- README.md
- package.json
- src/nodejs/neoscan/cli/get_last_transactions_by_address.js
- src/nodejs/neoscan/neoscan.js
.option('-t, --time', 'Only return time field of last transactions')
.option('-H, --Human', 'I am human so make outputs easy for human')
.option('-i, --index [index]', 'Only get last transactions up to i', 0)
> get_last_transactions_by_address cli arguments

- src/nodejs/email_alert.js
- src/nodejs/neoscan/cli/get_address_abstracts.js
- src/nodejs/neoscan/cli/get_all_nodes.js
- src/nodejs/neoscan/cli/get_balance.js
- src/nodejs/neoscan/cli/get_block.js
- src/nodejs/neoscan/cli/get_claimable.js
- src/nodejs/neoscan/cli/get_claimed.js
- src/nodejs/neoscan/cli/get_height.js
- src/nodejs/neoscan/cli/get_last_block.js
- src/nodejs/neoscan/cli/get_last_block_time.js
- src/nodejs/neoscan/cli/get_last_transactions_by_address.js
- src/nodejs/neoscan/cli/get_transaction.js
- src/nodejs/neoscan/cli/get_unclaimed.js
Some cleanup and argument passing groundwork
> Consistency Checks

- README.md
- package.json
- src/nodejs/config/config.js
- src/nodejs/monitor/cli/new_transaction_alert_loop.js
- src/nodejs/neoscan/cli/get_last_transactions_by_address.js
- src/nodejs/neoscan/modules/get_last_transactions_by_address.js
- src/nodejs/neoscan/neoscan.js
- src/nodejs/util/alert/email.js
- src/nodejs/util/debug.js
- added new_transaction_alert_loop.js
- created src/nodejs/neoscan/module/get_last_transaction_by_address.js that is called by cli wrapper get_last_transaction_by_address.js. This will be the basis for the wrapper technology.
> New Transaction Alert Loop

- src/nodejs/monitor/cli/new_transaction_alert_loop.js
The Subject was not being set properly. This should've been bugfix, but now the feature works so it's a feature. ;)
This also sets the alert detection to run  before an initial timeout.
> fix(new_transaction_alert_loop): Set alert subject

- src/nodejs/monitor/cli/new_transaction_alert_loop.js
- Renamed argz to runtimeArgs per review suggestion
- Removed unneeded print statement
> chore(new_transaction_alert_loop): runtimeArgs and unneeded print

- README.md
- package.json
- src/nodejs/neon-js/cli/rpc/getBlock.js
- src/nodejs/neon-js/modules/getBlock.js
- src/nodejs/neon-js/modules/get_last_transactions_by_address.js
- broke neon-js getBlock into CLI and module components for comosability
- added template to start neon-js-based get_last_transactions_by_address composition
> feat(neon-js/cli/rpc): modularize getBlock

- README.md
- package.json
- src/nodejs/config/config.js
- src/nodejs/config/nodejs.config.json
- src/nodejs/config/sample.config.json
- src/nodejs/neon-js/cli/rpc/getBlock.js
- src/nodejs/neon-js/cli/rpc/getBlockCount.js
- src/nodejs/util/network.js
- config system can now store nodes
- network.resolveNetworkId()
- network.getNodesByTallst()
- network.getNodesByLeastConnections()
- network.getNodesByVersion()
- getBlockCount now has dynamic node selection if no node is specified at CLI argument
> Feat(nodejs/src/): Config, Network Utils, and Some New Functions

- README.md
- package.json
- src/nodejs/neon-js/cli/rpc/getBestBlockHash.js
- src/nodejs/neon-js/cli/rpc/getBlock.js
- src/nodejs/neon-js/cli/rpc/getBlockCount.js
- src/nodejs/neon-js/cli/rpc/getVersion.js
- src/nodejs/neon-js/modules/getBlock.js
- src/nodejs/util/network.js
- Add getBlock() dynamic node selection
- Add getBestBlockHash() dynamic node selection
- Fix network.getNodesByTallest() stall 
- Added ping detection to getNodesByTallest
- Added network.getNodesByPing()
> Chore(nodejs/src/neon js)

- src/nodejs/monitor/cli/new_transaction_alert_loop.js
- src/nodejs/neon-js/modules/get_last_transactions_by_address.js
- src/nodejs/neoscan/modules/get_last_transactions_by_address.js
This is just an update to some of the status message printing of activity for the looping system.
There are a couple of todos added in some other random files.
> new transaction alert loop verbose status

- README.md
- package.json
- src/nodejs/account/account.js
- src/nodejs/config/config.js
- src/nodejs/exchange/binance/cli/get_asset_detail.js
- src/nodejs/monitor/cli/new_transaction_alert_loop.js
- src/nodejs/neo-rpc/v2.9.0/client/cli/getNodesBy.js
- src/nodejs/neo-rpc/v2.9.0/client/cli/neo-rpc.js
- src/nodejs/neo-rpc/v2.9.0/client/module/neo-rpc.js
- src/nodejs/neon-js/extension/cli/rpc/getLastTransactionsByAddress.js
- src/nodejs/neon-js/extension/modules/rpc/getLastTransactionsByAddress.js
- src/nodejs/neon-js/native/cli/rpc/getAccountState.js
- src/nodejs/neon-js/native/cli/rpc/getBestBlockHash.js
- src/nodejs/neon-js/native/cli/rpc/getBlock.js
- src/nodejs/neon-js/native/cli/rpc/getBlockCount.js
- src/nodejs/neon-js/native/cli/rpc/getRawTransaction.js
- src/nodejs/neoscan/cli/get_address_abstracts.js
- src/nodejs/neoscan/cli/get_balance.js
- src/nodejs/neoscan/cli/get_claimable.js
- src/nodejs/neoscan/cli/get_claimed.js
- src/nodejs/neoscan/cli/get_last_transactions_by_address.js
- src/nodejs/neoscan/cli/get_unclaimed.js
- src/nodejs/neoscan/modules/get_last_transactions_by_address.js
- src/nodejs/neoscan/neoscan.js
- src/nodejs/util/alert/email.js
- src/nodejs/util/network.js
> Feat(neo-rpc): Dynamic RPC method invocation from CLI

- README.md
- package.json
- src/nodejs/neo-rpc/v2.9.0/client/cli/getNodesBy.js
- src/nodejs/neon-js/native/cli/rpc/getConnectionCount.js
- src/nodejs/neon-js/native/cli/rpc/getPeers.js
- src/nodejs/neon-js/native/cli/rpc/getRawMemPool.js
- src/nodejs/neon-js/native/cli/rpc/getVersion.js
- src/nodejs/neon-js/native/cli/rpc/validateaddress.js
- src/nodejs/util/network.js
Specify a single node instead of using dynamic node selection as that pings all nodes in a net to find the best.
getNodesByX single node option
-n --node CLI option
Updated readme
Renamed files in neon-js for camel case matching
> chore(updates): Docs, camel casing, and a couple of features

- README.md
- package.json
- src/nodejs/monitor/cli/new_transaction_alert_loop.js
This option causes an alert if the most recent transaction is younger than that many minutes.
> Feat(alerts): add -y --youngerThan option to new_transaction_alert_loop

- README.md
- package.json
- src/nodejs/neo-rpc/v2.9.0/client/cli/getNodesBy.js
- src/nodejs/neo-rpc/v2.9.0/client/cli/query.js
- src/nodejs/neo-rpc/v2.9.0/client/module/getNodesBy.js
- src/nodejs/neo-rpc/v2.9.0/client/module/query.js
- src/nodejs/neon-js/extension/cli/rpc/getLastTransactionsByAddress.js
- src/nodejs/neon-js/native/cli/rpc/getAccountState.js
- src/nodejs/neon-js/native/cli/rpc/getBestBlockHash.js
- src/nodejs/neon-js/native/cli/rpc/getBlock.js
- src/nodejs/neon-js/native/cli/rpc/getBlockCount.js
- src/nodejs/neon-js/native/cli/rpc/getRawTransaction.js
- src/nodejs/neoscan/neoscan.js
- src/nodejs/node_results
- src/nodejs/util/network.js
- added getNodesBy module
- order by option
- renamed and reorganized network utils
> Feat(neo rpc): getNodesBy

- README.md
- package.json
- src/nodejs/monitor/cli/new_transaction_alert_loop.js
- src/nodejs/node_results
- fixed cli arguments
- updated to simpler search method using neoscan.get_address_abstracts
- fixed alert message body details
> Chore/monitor:  new_transaction_alert_loop improvements

- src/nodejs/config/sample.config.json
- src/nodejs/neo-rpc/v2.9.0/client/cli/getNodesBy.js
- src/nodejs/neo-rpc/v2.9.0/client/module/getNodesBy.js
There were bugs in node operation between automatically picking network nodes.
Logging is now much more verbose.
> Chore/neo-rpc: getNodesBy Logging and Bug Fix

- README.md
Minor documentation updates
- clone steps
- typos
- clarity around neo-rpc
> chore/docs: build steps and miscellaneous

- README.md
- package.json
- src/nodejs/account/account.js
- src/nodejs/account/cli/getNep2EncryptedKey.js
- src/nodejs/account/cli/list.js
- src/nodejs/account/cli/watch.js
- src/nodejs/config/sample.config.json
- Configuration updates
- Readme updates
- src/nodejs/account/getNep2EncryptedKey.js
- account.getNep2EncryptedKey()
> Feat/wallet: NEP-2 Storage Support

- README.md
- package.json
- src/nodejs/account/cli/decryptNep2.js
Added src/nodejs/account/cli/decryptNep2.js to decrypt NEP-2 keys from account configuration
> feat/wallet: decryptNep2 CLI

- README.md
- package.json
- src/nodejs/account/account.js
- src/nodejs/account/cli/decryptNep2.js
- src/nodejs/account/cli/getNep2EncryptedKey.js
- src/nodejs/account/cli/list.js
- src/nodejs/account/modules/decryptNep2.js
This also includes some cleanup.
> Feat/wallet: add decryptNep2 module for reusability

- README.md
- package.json
- src/nodejs/neon-js/native/cli/rpc/getAccountState.js
- src/nodejs/neon-js/native/cli/rpc/getBestBlockHash.js
- src/nodejs/neon-js/native/cli/rpc/getBlock.js
- src/nodejs/neon-js/native/cli/rpc/getBlockCount.js
- src/nodejs/neon-js/native/cli/rpc/getRawTransaction.js
- src/nodejs/rpc-over-https/v2.9.0/client/cli/getNodesBy.js
- src/nodejs/rpc-over-https/v2.9.0/client/cli/query.js
- src/nodejs/rpc-over-https/v2.9.0/client/module/getNodesBy.js
- src/nodejs/rpc-over-https/v2.9.0/client/module/query.js
- src/nodejs/transactions/cli/contract.js
- src/nodejs/transactions/modules/contract.js
Renamed neo-rpc to rpc-over-https
Upgraded getNodesBy
- added -l --list to specify a list of stats to collect from each node
- refined object counting and verbosity
- some reliability enhancements
> Feat/wallet: upgrade rpc-over-https and getNodesBy

- src/nodejs/neo-rpc/v2.9.0/client/module/query.js
Reverts CityOfZion/neo-tools#90
> Revert "Update query.js"
